export enum AuthActionTypes {
  USER_LOADED = 'USER_LOADED',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',
  USER_LOADING = 'USER_LOADING',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  AUTH_FAIL = 'AUTH_FAIL',
  AUTH_SUCCESS = 'AUTH?SUCCESS',
  CLEAN_ERRORS = 'CLEAN_ERRORS',
}

export enum ProductActionTypes {
  LOADING = 'LOADING',
  LOADING_FAILED = 'LOADING_FAILED',
  LOADING_SUCCESS = 'LOADING_SUCCESS',
}
